theme: jekyll-theme-minimal

title: Ethical & Effective Visualization
tagline: A method for ethically visualizing data
description: Originally developed for big data and medium data contexts in the digital humanities, this method is currently also being used by tech startups, and in visualization of broader impacts by research groups in the humanities, sciences, and social sciences.
show_downloads: false
url: https://kathep.github.io

collections:
  versions:
    output: true

defaults:
  - scope:
      path: ""
      type: "versions"
    values:
      layout: "version"
  - scope:
      path: ""
    values:
      layout: "default"
