theme: jekyll-theme-minimal

title: Ethical and Effective Visualization
tagline: A method for ethically visualizing data
description: Originally developed for big data and medium data contexts in the digital humanities, this method is currently also being used by tech startups, and in visualization of broader impacts by research groups in the humanities, sciences, and social sciences.
test: Extra content
show_downloads: false
